### PR TITLE
Docs section 03

### PR DESCRIPTION
**Pull request by SantiFC12**
Remember it is just an initial version.

### CODE REVIEW

**Comment by UO283216** [comment]
I will reconsider the addition of the email in the business context diagram since for now we do not have any kind of need to send emails to the user and I believe application notifications would better be presented directly when login rather than via email.

I will add a bit more information on the first section deffining what is the docummentation between each of the represented modules as the documentation of that section indicates: " with explanations of domain specific inputs and outputs or interfaces".

I will elaborate a little bit more on each of the technical context. As an example I would write something like "It will be the infrastructure that will host both application and database, communication with this element will be avoided by means of the use of docker containers that will abstract the application from the machine" in the "Hosting server" section. And try to copy that format of explaining what are the inputs and outputs of that context and why it is important.

**Comment by SantiFC12** [comment]
Ok, I can remove the email and if in the future we need it we can always add it again. I can also add a little more content to the table of the Technical Context.

For your other suggestions, I need you to be a bit more specific, if you don't mind. We can explain the Business Context with just the diagram and more information is optional. I think we can always be more specific and are more things later. But again, I can try to add the things you suggest if you explain better.

**Comment by SantiFC12** [comment]
I removed the Email box from the diagram and the Technical Context table is now much more detailed.

**Comment by UO283216** [comment]
I'd add in the first section for each of the elements in the diagram an explanation of what the expected input and outputs are. For example for the interaction of usr-Solid pod has input: user credentials and as output the allowance of our application to access the usr's pod. 

Something like this, small text explaining the interaction that makes diagram clearer.

I think it is better explained this way but for now it can be enough to leave it as it is. It is up to you.

**Comment by garciafdezpatricia** [comment]
i think that what Pablo says is a good idea: add what it is expected to send to and receive from the elements. Apart from this I would not have much more to add. Maybe when we progress with the implementation we will have more clues about what to add here.

**Review by UO283216 — APPROVED** [review]
For now it is okay, we will make it  more complete as we develop.

**Pull request merged**
