### PR TITLE
Section 9 doc (design decisions)

### PR DESCRIPTION
**Pull request by garciafdezpatricia**
I filled the section with some information. Review it and tell me :)
Apart from that, I want to ask you about the ARD Links: what do you think of having them included in this doc? Also, I added the information we talked about in the last meeting (decentralized data and heroku) but as we did not write an ARD for them, should we do it?

### CODE REVIEW

**Review by UO283216 — COMMENTED** [review]
Maybe delete the titles of ARDs that do not have a link for no missunderstanding of it not being completed but seem correct. 
Heroku is still to be confirmed and maybe leave it more like a possibility more than a decision already taken

**Comment by garciafdezpatricia** [comment]
okei, changes corrected :)

**Review by UO283216 — APPROVED** [review]
Now it is perfect. :)

**Review by UO282365 — APPROVED** [review]
Good work, for me it's ok. Regarding the ARD I think it would be good to discuss it during tomorrow's session.

**Comment by SantiFC12** [comment]
I approve.

**Review by SantiFC12 — APPROVED** [review]

**Pull request merged**
