### PR TITLE
Filter locations of the map by categories - patri

### PR DESCRIPTION
**Pull request by garciafdezpatricia**
New functionalities:
- Added buttons on top of the map with predefined categories (Shop, Sight, Bar, Other, ...). When any of these buttons is clicked, the map displays only the locations corresponding to those categories (multiple filtering not supported at the moment).
- Added categories on the form of adding locations to choose one when creating a new place. Can assign multiple categories to the location. (Did not do validation checks when submitting the form, such as "you need to select a category").
- Added drop down friend filtering (not implemented, friend logic still pending). The friend drop down is filled with categories only to have something inside.

New class added: Category.ts. Contains the enum of the categories and some util methods to serialize them. 

The new content is easy to change if we decide to make the categories in a different way.

Check that is working fine in your machines and let me know :)

### CODE REVIEW

**Comment by UO283216** [comment]
Idk why but it is not working for me, when I add a location the location is not added neather to the list neather to the map. May be caused due to not merging it with recent changes?

**Comment by garciafdezpatricia** [comment]
The code is not adding any locations? that is strange. I dont know if it could be due to the merging cause it was merged with the recent changes of the solid management. Maybe we could do a call to try to fix it?

**Comment by garciafdezpatricia** [comment]
Error located:
I saw that when you try to retrieve from the pod a location that hasnt a category, it fails. In the code there is a try-catch, so when the error is raised the array of locations is sset to [ ]. That is the reason why we cant see the locations.

I think we need to take a decision: do we want to make the user able to add a location without a category? if we want to, I only have to change the getLocations method.

**Comment by UO283216** [comment]
Retried now and works perfect. 👌

**Review by UO283216 — APPROVED** [review]

**Comment by UO283216** [comment]
Now works even better thanks to the change in #98

**Pull request merged**
