### PR TITLE
Section 4 documentation.

### PR DESCRIPTION
**Pull request by UO282365**
Section 4 documentation. Please take a look and review it carefully.

### CODE REVIEW

**Comment by SantiFC12** [comment]
You can also add the MVC pattern in the Design part.
I think that the rest is fine.

**Review by garciafdezpatricia — COMMENTED** [review]
I think the same as Santi. Apart from that, I dont have anything more to add.
In the first lines there is a 'with' (whith) and 'will' (whill) mispelled. Also 'powerful' (powerfull) and i think that 'containerizes' (conteinerizes).

**Review by UO283216 — APPROVED** [review]
I would use '===' for the subsections for it to follow the rest of the sections format. But contents seem perfect for now

**Review by SantiFC12 — APPROVED** [review]
Approved.

**Pull request merged**
