### PR TITLE
Documentation section2

### PR DESCRIPTION
**Pull request by UO283216**
Addition of the second section for the documentation for it to be reviewed.

### CODE REVIEW

**Comment by SantiFC12** [comment]
I think that it's fine and well explained.

**Review by garciafdezpatricia — COMMENTED** [review]
I agree with the contents of the section. Each constraint and explanation seems right to me and i cant think of any other to add at the moment

**Comment by UO282365** [comment]
I think it's very good as a first approach. I like the use of a table to show the different constraints, since it's more visual.

**Comment by UO282365** [comment]
Since every team memeber has reviewed this pull req, I proceed to merge it with develop.

**Review by UO282365 — APPROVED** [review]
I think it's very good as a first approach. I like the use of a table to show the different constraints, since it's more visual.

**Pull request merged**
