### PR TITLE
Section 1 doc

### PR DESCRIPTION
**Pull request by UO282365**
First approach to section 1 documentation. Please review it carefully and send feedback.

### CODE REVIEW

**Comment by UO283216** [comment]
It seems perfect in most of the places, I would refactor the first section "Intruduction and Goals" because I think it lacks a bit of the background of the application (maybe add name of the company) and maybe write it all on the same paragraph for it to look a bit more related. 
I also spotted a missing punctuation symbol rigth after the link to the lab assigment. 
Lastly I would also include the company to the stakeholders section since we are simulating the application development task is given to us by them and the are the ones in charge of requirements (still I will mantain professors in the stakeholder section since even though we are simulating they are interested in the final product).
Besides these little remarks for me it seems a pretty good first approach 👍.

**Review by garciafdezpatricia — COMMENTED** [review]
About the introduction I think the same as Pablo, maybe add more background and put all in one paragraph to make it more compact.

In the requirements i think that there is one missing, the one that says that the information must not be centralized. Although it is explained in another paragraph i think that it is important that we have the same number of high level requirements that the teachers gave us.
Also, even though we are not sure about doing the optional requirements maybe it will be better to write them down rather than link them to show that at least we read them xd
Esto lo pongo en español pa explicarlo mejor. Hay una forma que se suele usar para escribir los requisitos que es poner el actor del sistema junto con el requisito, por ejemplo:
"Yo, como usuario, quiero poder controlar la informacion que comparto con mis amigos" así se evitan confusiones sobre quien lo puede hacer y quien no. Igual estaria bien ponerlos asi.

About the stakeholders I think that what Pablo said is alright, the company that we are supposed to impersonate should be added as a stakeholder. Also I think the council of Brussels is an important one, since it is our sponsor. Maybe the companies empathy and intrust too? since they are interested in the development of the project

**Comment by UO282365** [comment]
I've read your feedback. I'm going to make some changes to it and upload it. 
About the optional requirements that @garciafdezpatricia has mentioned, since we have not really talked about it, I think it's better to wait until tomorrow and discuss it with our professors if they have to be decided now or not.
Also, I considered the story user way of writting functionality, but I think it suits better as a way of define functionality at the issues when we start to implement them, and leave this requirements as a more general view.
Anyways, as this is a first approach, it's good that this questions arise, since we still have plenty of time and we can discuss with our professors.

**Comment by garciafdezpatricia** [comment]
@UO282365 We have asked the teachers about the way of describing requirements and the optional ones.

1. He said that the way of describing the functional requirements as long as they are clear is okay. That maybe we should divide them in the ones of the user and the ones of the system. Like The user can: 1. .... 2. .... ; The system must: 1. .... 2. ..... ......
2. The optional requirements must appear in the documentation.

**Comment by UO282365** [comment]
The section has been updated. Please check it out.

**Review by SantiFC12 — APPROVED** [review]

**Comment by UO283216** [comment]
Now it seems perfect. 🐒👍

**Review by UO283216 — APPROVED** [review]

**Pull request merged**
