### PR TITLE
Possible contents for section 11 (Risks)

### PR DESCRIPTION
**Pull request by garciafdezpatricia**
Section 11 containing the possible risks of the projects filled. I left the sub section of technical debts blank because i dont really get the meaning of a 'technical debt' and i was planning on asking the teachers about it

### CODE REVIEW

**Comment by SantiFC12** [comment]
I think that the information and the explanations are great, but I would change something. The first and third columns are a little bit unconnected, I think. For example if you read "Unexpertised on React" and then read "Probability very high". 
I don't know if I'm explaining myself correctly. I'd change the first column to something like "Problems while using React" or "Not understanding React". Now it makes more sense, because the probability to have problems with it is very high.
And the case is very similar in the other rows of the table.

**Comment by garciafdezpatricia** [comment]
> 
Okei, I will change the names. I included the sections of impacts and probability to try add some information apart from the risk itself and the solution but maybe is not needed

**Comment by UO283216** [comment]
For me it is pretty good for this first iteration on the documentation. I would also change what Santiago pointed out but it seems perfect for now this way.
👍

**Comment by garciafdezpatricia** [comment]
I have updated the names of the risk just now, let me know if they are better or if I can improve any of them :)

**Comment by UO283216** [comment]
Now it seems perfect for me ;)

**Comment by UO282365** [comment]
I think it's fine

**Pull request merged**
