### PR TITLE
Review + Scores functionality

### PR DESCRIPTION
**Pull request by garciafdezpatricia**
Reviews and Scores functionality now working, both in the UI and in the pod. Check if everything is working for you too, now that the pod management is included :)

### CODE REVIEW

**Comment by UO283216** [comment]
Idk why but images are not shown correctly on my locations, even if i add a new one with images. 🤦

**Comment by UO283216** [comment]
I think I now understand the problem that we have with the images. I believe the problem is the size of the images. Created new issue to discuss it and give it a solution -> #104

**Comment by UO283216** [comment]
I think this pr can be pushed into develop because (#104 ) is a minor bug we will solve in the future.

**Review by UO283216 — APPROVED** [review]

**Review by SantiFC12 — APPROVED** [review]
Tested and everything works fine.

**Pull request merged**
