### PR TITLE
Add location button on corner

### PR DESCRIPTION
**Pull request by UO283216**
This pull requests includes a lot of new features, views and bug fixes:
- #168
- #161 
- #169
- #146 
- #130

### CODE REVIEW

**Comment by UO283216** [comment]
Also fixed bug:
- #143

**Comment by garciafdezpatricia** [comment]
It is great! Great great work! Only two things:
- The 'List of Locations' title is breaking a little with the style of the other views, I mean:
imagen
imagen

- I would make this icon a lil smaller but is just my perfectionism talking:
imagen

Anyways, great work makina :)

**Review by garciafdezpatricia — APPROVED** [review]

**Review by UO282365 — APPROVED** [review]
You really did a great job 🤓🎉. I like the new feeling of the app.

**Review by SantiFC12 — APPROVED** [review]
Great job. The app now looks amazing.

I just have one little thing to say. I don't think the map should be centered when you click to add a location, just when you click one that already exists. 
To me, it feels weird. I understand if you like it how it is now and you don't want to change that. Again, great job!

**Comment by SantiFC12** [comment]
I will explain better. I think that as a user, when you are told to click the map to add the location, you expect the pin to appear just where the mouse is. But with the sudden movement of the map, the mouse stays in one place and the pin appears in another place. I think that can give the user the sensation that the pin did not appear where they wanted to. At least, that is what happened to me.

**Comment by UO283216** [comment]
Solved @garciafdezpatricia title suggestion.
Did not solve the X icon size since i believe view is quite simple and no issue on the size.
Solved @SantiFC12  suggestion to not set center on addition of location (you were rigth, looked akward)
Added that when selecting the locations in the lists it also centers the selected location. This way you know where it is.

**Pull request merged**
