### PR TITLE
Section-8-docs

### PR DESCRIPTION
**Pull request by SantiFC12**
This is the initial version. The diagram lacks a lot of information. If you have any idea of what to add, tell me. Of course it is inevitable that it'll change once we begin the implementation.

### CODE REVIEW

**Comment by UO283216** [comment]
I believe you are missing the Users in the domain model, they have to be modelled in order to represent information on the logged user and also relationships between the different users. Later we may have different types of users and they will all deppend on some sort of interface but for now i will just add the User as it is. 
I will delete the location object and move information on what you call a Place and rename it to Location for it to match the other places of the documentation.
Adding these two changes I believe it is perfect for now.

**Review by garciafdezpatricia — COMMENTED** [review]
I think it is fine, I mean, we do not know anymore of the domain model because we did not get into it yet. I think the moment we start programming and seeing the whole picture, this section would be more complete. 
The only thing regarding the domain that occurred to me was, maybe, introducing the entity of Review as a list in the Place class, to somehow be able to store all the possible reviews the users want to add to a place.
Lastly, there is an errata in a word: 'ir' instead of 'it'.

**Comment by UO282365** [comment]
I think the same as Pablo, with that changes it would be fine for now.👍

**Review by UO283216 — APPROVED** [review]
Now it is perfect :)

**Pull request merged**
